# Where should we write the GIF?
Output ./docs/demo.gif

# Set up a 1200x600 terminal with 46px font.
Set FontSize 20
Set Width 1200
Set Height 600

Type "cd zig-out/bin && ./kiwiwi cry"
Sleep 500ms
Enter

Type "./kiwiwi doctor"
Sleep 500ms
Enter

Type "./kiwiwi new"
Sleep 700ms
Enter

Type "./kiwiwi s greeting"
Sleep 500ms
Enter

Type "./kiwiwi co greeting get"
Sleep 500ms
Enter

# Admire the output for a bit.
Sleep 3s
